#lang ivy 1.8

# Abstract model and proof of liveness of Bakery protocol

include order

# both tickets and threads are ordered. Each thread has its own thread ID,
# which is used for tie-breaking when ticket IDs are the same.
instance thread : unbounded_sequence
instance ticket : unbounded_sequence

type location = {idle, picking, waiting, critical}

individual pc(T:thread) : location
individual number(T:thread) : ticket

# `front` records the thread with the least ticket that is pending.
# in other words, the `front` thread is the one waiting to enter critical section.
var has_front : bool
individual front : thread

## become_critical(T) whenever T is allowed to enter the critical section.
# 1. No other thread is in the 'choosing' phase.
# 2. For all others, either they have ticket '0' (idle), 
#    or my (ticket, id) is lexicographically smaller than theirs.

relation lexlt(T1:thread, T2:thread) = # true iff T1 is less than T2 lexicographically.
  number(T2) = 0 | number(T1) < number(T2) | (number(T1)=number(T2) & T1 < T2)


# a thread T can take control of the critical section when
# for all other threads O, (T's number, T's ticket) < (O's number, O's ticket)
relation become_critical(T:thread) = 
  forall O:thread. O~=T -> lexlt(T, O) #(O ~= T -> (~choosing(O) & lexlt(T,O)))

## fairness constraints
relation fair_start_picking(T:thread)
relation fair_waiting(T:thread)
relation fair_critical(T:thread)
relation fair_leave_critical(T:thread)

after init {
    pc(T) := idle;
    number(T) := 0;     
    has_front := false;

    fair_start_picking(T) := false;
    fair_waiting(T) := false;
    fair_critical(T) := false;
    fair_leave_critical(T) := false;
}

# Step 1: Start picking a ticket
action start_picking(t:thread) = {
    
    fair_start_picking(t) := true;
    fair_start_picking(t) := false;

    if pc(t) = idle {
      pc(t) := picking;
    }
}

# Step 2: Finish picking a ticket n for thread t
action finish_picking(t:thread, n: ticket) = {
    require n > 0; # enforce positive number
    require forall T:thread. number(T) < n; # We assume we pick a ticket strictly greater than any currently held.
    
    fair_waiting(t) := true;
    fair_waiting(t) := false;

    if pc(t) = picking {
      if ~has_front {
        front := t; # there's a thread waiting to enter critical section when at least one thread has picked a ticket.
        has_front := true;
      };
      number(t) := n;
      pc(t) := waiting;
    }
}

# Step 3: Enter Critical Section
action enter(t:thread) = {
    
    fair_critical(t) := true;
    fair_critical(t) := false;

    if pc(t) = waiting & become_critical(t) {
      pc(t) := critical;
    }
}

# Step 4: Leave Critical Section
action leave(t:thread) = {
    
    fair_leave_critical(t) := true;
    fair_leave_critical(t) := false;

    if pc(t) = critical {
      # Maintain the `front` prophecy variable. Choose the least remaining
      # live ticket as the new front.
      if some f:thread. f ~= t & number(f) > 0 minimizing number(f) {
        front := f;
      } else {
        has_front := false;
      };
      number(t) := 0;
      pc(t) := idle;
    }
}

# Mutex property
invariant [mutex] (pc(T1) = critical & pc(T2) = critical) -> T1 = T2

# supporting invariants
invariant [valid_ticket] (pc(T) = waiting | pc(T) = critical) -> number(T) > 0
invariant [no_ticket_idle] (pc(T) = idle | pc(T) = picking) -> number(T) = 0

# Similar to the ticket protocol here we prove that
# each thread holds a unique ticket, and `front` is the least-ticket holder. 
invariant [unique_ticket]
  (number(T1) > 0 & number(T2) > 0 & number(T1) = number(T2)) -> T1 = T2

invariant [front_number] has_front -> number(front) > 0
invariant [front_exists] number(T) > 0 -> has_front
invariant [front_is_least]
  (has_front & number(T) > 0) -> (front = T | number(front) < number(T))

invariant [pending_threads]
  number(T) > 0 -> (pc(T) = waiting | pc(T) = critical)
invariant [critical_thread]
  pc(T) = critical -> (has_front & T = front)
invariant [front_critical] has_front -> become_critical(front)

# If T1 is critical, and T2 has a ticket, T1 must be "smaller" than T2.
invariant [critical_smallest] (pc(T1) = critical & T1 ~= T2 & number(T2) > 0) ->
    (number(T1) < number(T2) | (number(T1) = number(T2) & T1 < T2))

# fairness invariants
invariant ~fair_start_picking(T)
invariant ~fair_waiting(T)
invariant ~fair_critical(T)
invariant ~fair_leave_critical(T)

export start_picking
export finish_picking
export enter
export leave

# Liveness

# If a thread is waiting, it eventually enters critical section subject to assumptions.
explicit temporal property [starvation_freedom] 
  (
    (forall T. globally eventually fair_start_picking(T)) &
    (forall T. globally eventually fair_waiting(T)) & 
    (forall T. globally eventually fair_critical(T)) & 
    (forall T. globally eventually fair_leave_critical(T))
  ) ->
  (
    forall T. globally (pc(T) = waiting -> eventually pc(T) = critical)
  )
proof {
  tactic skolemizenp;
  tactic ranking with {
    # The high-order component is the set of pending threads.
    definition work_created[0](T:thread) = number(T) > 0
    definition work_needed[0](T:thread) =
      number(T) > 0 & (T = _T | lexlt(T, _T))
    definition work_invar[0] = pc(_T) = waiting
    definition work_progress[0](T:thread) = fair_leave_critical(T)
    definition work_helpful[0](T:thread) = has_front & T = front & pc(T) = critical

    # The low-order component tracks the thread that's about to enter critical section. 
    definition work_created[1](T:thread) = has_front & T = front
    definition work_needed[1](T:thread) = has_front & T = front & pc(T) = waiting
    definition work_invar[1] = pc(_T) = waiting
    definition work_progress[1](T:thread) = fair_critical(T)
    definition work_helpful[1](T:thread) = has_front & T = front & pc(T) = waiting
  }
}
